# Generated by Django 5.1.7 on 2025-03-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='car_name')),
                ('price', models.PositiveIntegerField(verbose_name='car_price')),
                ('image', models.ImageField(upload_to='cars', verbose_name='car_image')),
            ],
        ),
    ]
